init:
  - git config --global core.autocrlf true
 
image: Visual Studio 2017
 
before_build:
- choco install opencover.portable
- choco upgrade opencover.portable
- choco install codecov
 
build_script:
  - ps: .\build.ps1
  - OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results1.trx /p:DebugType=full test\Manga.Domain.Tests\Manga.Domain.Tests.csproj" -filter:"+[Manga.*]* -[*.Tests*]*" -output:".\my_app_coverage.xml" -oldstyle -mergeoutput
  - OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results2.trx /p:DebugType=full test\Manga.UseCases.Tests\Manga.UseCases.Tests.csproj" -filter:"+[Manga.*]* -[*.Tests*]*" -output:".\my_app_coverage.xml" -oldstyle -mergeoutput 
  - OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results3.trx /p:DebugType=full test\Manga.WebApi.Tests\Manga.WebApi.Tests.csproj" -filter:"+[Manga.*]* -[*.Tests*]*" -output:".\my_app_coverage.xml" -oldstyle -mergeoutput
  - codecov -f .\my_app_coverage.xml -t $(codecov_token)
 
test: off
 
branches:
  only:
    - dev
    - master
 
cache:
- tools -> build.cake
- packages -> build.cake